### PR TITLE
Don't throw exceptions for 404 get requests

### PR DESCRIPTION
**Pull request by bmac**
This makes it easier to write assertions for tests that are expected to 404.

### CODE REVIEW

**Comment by MattSurabian** [comment]
Code looks good per Guzzle docs :+1:

**Comment by jugglinmike** [comment]
Weird: I couldn't find this mentioned in the 5.3 docs. Likely location is here: https://github.com/guzzle/guzzle/blob/5.3/docs/quickstart.rst#exceptions , but nothing.

**Comment by MattSurabian** [comment]
http://guzzle3.readthedocs.org/http-client/client.html#exceptions

**Comment by MattSurabian** [comment]
also https://github.com/guzzle/guzzle/blob/5.3/docs/clients.rst#exceptions

**Comment by jugglinmike** [comment]
Now I'm all confused. Guzzle 3? [Isn't ae-api on 5.3?](https://github.com/wfmu/ae-api/blob/78dbbc321481329f6c4fe119efb2b7c6de4bdf73/composer.json#L5) And [what are these docs for Guzzle 6](http://docs.guzzlephp.org/en/latest/index.html)?

**Comment by MattSurabian** [comment]
Yeah I'm not sure what's up there, the second link is from the 5.3 docs.

**Comment by jugglinmike** [comment]
Roger that!

**Comment by jugglinmike** [comment]
Rebased and merged to `master` at commit 8c62a28fc0885854ac578a7df3dcd0da68b0036a

**Pull request closed without merging**
