### PR TITLE
Simplify route instantiation

### PR DESCRIPTION
**Pull request by jugglinmike**
The in-line comments contain a reference to the Slim framework. This makes me think that the structure here is a vestige of when that framework was a dependency. In any case, I think this is an improvement for readability and testability, as explained in the commit message:

> Remove cyclic relationship between Routes and Routers. This
>
> 1. Makes the code base easier to reason about. Control flows in one
>   direction only--the Router manages its Route instances, and Routes do
>   not need a reference to the Router to which they belong.
> 2. Better-facilitates testing. Fewer mocks are required to initialize a
>   Route subclass in a test environment.

### CODE REVIEW

**Comment by bmac** [comment]
:+1:

**Comment by jugglinmike** [comment]
@carldanley Does this look okay to you?

**Comment by carldanley** [comment]
Yes, I believe so. code :+1: tests :+1:

**Comment by jugglinmike** [comment]
Thanks!

**Comment by jugglinmike** [comment]
Rebased and merged to `master` at commit 68b50fce59bcc6bda4279b6209f828914d93adcc.

**Pull request closed without merging**
